defaults:
    - _self_
    - general : general_e2e
    - model : model_e2e
    - train : train_e2e
    - dataset : neims

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}