defaults:
    - _self_
    - general : general_test
    - model : model_test
    - train : train_test
    - dataset : atmomaccs

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}
