defaults:
    - _self_
    - general : general_encoder
    - model : model_encoder
    - train : train_encoder
    - dataset : neims

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}